server :
  port : 0 
  
---
spring:
   mvc:
      view:
         prefix: /WEB-INF/jsp/ 
         suffix: .jsp
         
---
spring:
   mvc:
      static-path-pattern: /static/**
   resources:
      static-locations: classpath:/static/
      
---
mybatis:
   type-aliases-package: com.hwadee.smbms.model
   mapper-locations: classpath:mapper/*.xml
---
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
   
   